# Create schema
# https://learn.microsoft.com/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-1.0&tabs=http
# https://learn.microsoft.com/graph/connecting-external-content-manage-schema?context=%2Fmicrosoft-365-copilot%2Fextensibility%2Fcontext

# Note:
# Schema determines how content indexed, queried, and retrieved from the search index
# Use semantic labels to improve queries. iconUrl, title, and url labels must be used for Microsoft 365 Copilot

# @name createSchema
PATCH https://graph.microsoft.com/v1.0/external/connections/marvelcharacters/schema
Content-type: application/json
Authorization: Bearer {{$aadV2Token appOnly}}

{
	"baseType": "microsoft.graph.externalItem",
	"properties": [
		{
			"name": "title",
			"type": "string",
			"isQueryable": true,
			"isSearchable": true,
			"isRetrievable": true,
			"labels": [
				"title"
			]
		},
		{
			"name": "realName",
			"type": "string",
			"isQueryable": true,
			"isSearchable": true,
			"isRetrievable": true,
		},
		{
			"name": "url",
			"type": "string",
			"isRetrievable": true,
			"labels": [
				"url"
			]
		},
		{
			"name": "iconUrl",
			"type": "string",
			"isRetrievable": true,
			"labels": [
				"iconUrl"
			]
		},
		{
			"name": "description",
			"type": "string",
			"isQueryable": true,
			"isSearchable": true,
			"isRetrievable": true
		}
	]
}

###

# Get schema provisioning status
# https://learn.microsoft.com/graph/api/externalconnectors-connectionoperation-get?view=graph-rest-1.0&tabs=http

# Note:
# The URL to get the operation status is returned in the Location header of the createSchema response. The process can take between 5-10 minutes to complete.

@operationStatusUrl = {{createSchema.response.headers.Location}}

# @name getOperationStatus
GET {{operationStatusUrl}}
Authorization: Bearer {{$aadV2Token appOnly}}
