# Delete connection
# https://learn.microsoft.com/graph/api/externalconnectors-externalconnection-delete?view=graph-rest-1.0&tabs=http

# @name deleteConnection
DELETE https://graph.microsoft.com/v1.0/external/connections/marvelcharacters
Authorization: Bearer {{$aadV2Token appOnly}}